apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chf-lun-pvc-v2
  namespace: chf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-lun
