apiVersion: v1
kind: Pod
metadata:
  name: secret-test
  namespace: upf-w
spec:
  containers:
  - name: nginx
    image: nginx:1.27-alpine
    volumeMounts:
    - name: diameter-creds
      mountPath: /etc/upf/secrets
      readOnly: true
  volumes:
  - name: diameter-creds
    secret:
      secretName: upf-diameter
      defaultMode: 0400
